package com.examguard.web.rest;

import com.examguard.domain.*;
import com.examguard.repository.*;
import com.examguard.security.SecurityUtils;
import com.examguard.service.dto.ExamTakingDTOs.*;
import com.examguard.web.rest.errors.*;

import java.time.Instant;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

/**
 * This controller is 100% hand-written business logic — nothing here was
 * generated by JHipster. It sits ALONGSIDE the generated ExamResource,
 * QuestionResource, AttemptResource (which still exist for teacher CRUD:
 * creating exams, adding questions). This class only handles the actual
 * "taking an exam" flow, which is specific to your project and something
 * no generator could know about.
 *
 * Kept as its own class (not stuffed into the generated AttemptResource)
 * so that in the viva you can point at ONE file and say "this is the part
 * I wrote myself."
 */
@RestController
@RequestMapping("/api")
public class ExamTakingResource {

    private final ExamRepository examRepository;
    private final QuestionRepository questionRepository;
    private final AttemptRepository attemptRepository;
    private final StudentAnswerRepository studentAnswerRepository;
    private final ProctorEventRepository proctorEventRepository;
    private final UserRepository userRepository;

    @Autowired
    public ExamTakingResource(
        ExamRepository examRepository,
        QuestionRepository questionRepository,
        AttemptRepository attemptRepository,
        StudentAnswerRepository studentAnswerRepository,
        ProctorEventRepository proctorEventRepository,
        UserRepository userRepository
    ) {
        this.examRepository = examRepository;
        this.questionRepository = questionRepository;
        this.attemptRepository = attemptRepository;
        this.studentAnswerRepository = studentAnswerRepository;
        this.proctorEventRepository = proctorEventRepository;
        this.userRepository = userRepository;
    }

    /**
     * Small helper: get the currently logged-in student as a User entity.
     * SecurityUtils.getCurrentUserLogin() reads the username out of the
     * JWT token that Spring Security already validated for this request.
     */
    private User currentUser() {
        String login = SecurityUtils.getCurrentUserLogin()
            .orElseThrow(() -> new UnauthorizedAccessException("Not logged in"));
        return userRepository.findOneByLogin(login)
            .orElseThrow(() -> new ResourceNotFoundException("User not found: " + login));
    }

    // =====================================================================
    // RULE 1: Start-attempt logic
    // POST /api/exams/{examId}/attempts
    // =====================================================================
    // @Transactional keeps the Hibernate session open for the whole method,
    // which is required here: we call q.getQuestionOptions() further down,
    // and that's a LAZY collection — Hibernate only fetches it from the
    // database the moment you actually call .get...(), not when the
    // Question itself was loaded. Without an open transaction, that lazy
    // fetch fails with "no session" because the session already closed.
    @Transactional
    @PostMapping("/exams/{examId}/attempts")
    public ResponseEntity<StartAttemptResponse> startAttempt(@PathVariable Long examId) {
        User student = currentUser();

        Exam exam = examRepository.findById(examId)
            .orElseThrow(() -> new ResourceNotFoundException("Exam not found: " + examId));

        // --- duplicate-attempt check (Unit I: custom exception) ---
        // We check the database, not just "does the student remember
        // starting it", because two tabs/requests could race — the real
        // safety net is the UNIQUE constraint on (exam_id, student_id) in
        // the Attempt table, which we set up in the JDL. This check just
        // gives a friendlier error before hitting that constraint.
        boolean alreadyAttempted = attemptRepository
            .findAll()
            .stream()
            // defensive: skip any malformed row (e.g. created via the
            // generic CRUD screen with a missing exam or student) instead
            // of crashing this check for every other attempt too
            .filter(a -> a.getExam() != null && a.getStudent() != null)
            .anyMatch(a -> a.getExam().getId().equals(examId) && a.getStudent().getId().equals(student.getId()));
        if (alreadyAttempted) {
            throw new DuplicateAttemptException("You have already attempted this exam.");
        }

        // --- server decides the time, not the browser ---
        Instant now = Instant.now();
        Instant endsAt = now.plusSeconds(exam.getDurationSeconds());

        Attempt attempt = new Attempt();
        attempt.setExam(exam);
        attempt.setStudent(student);
        attempt.setStartedAt(now);
        attempt.setEndedAt(endsAt);
        attempt.setSubmitted(false);
        attempt = attemptRepository.save(attempt);

        // Build the question list WITHOUT correctOptionIndex — that field
        // exists on the entity but we deliberately don't copy it into the
        // DTO sent to the student.
        List<QuestionForStudent> questions = questionRepository
            .findAll()
            .stream()
            .filter(q -> q.getExam() != null && q.getExam().getId().equals(examId))
            .map(q -> new QuestionForStudent(
                q.getId(),
                q.getText(),
                q.getQuestionOptions()
                    .stream()
                    .sorted(Comparator.comparingInt(QuestionOption::getOrderIndex))
                    .map(o -> new OptionForStudent(o.getId(), o.getText(), o.getOrderIndex()))
                    .collect(Collectors.toList())
            ))
            .collect(Collectors.toList());

        return ResponseEntity.ok(new StartAttemptResponse(attempt.getId(), endsAt, questions));
    }

    // =====================================================================
    // RULE 2: Answer-saving logic (auto-save)
    // POST /api/attempts/{attemptId}/answers
    // =====================================================================
    @PostMapping("/attempts/{attemptId}/answers")
    public ResponseEntity<SaveAnswerResponse> saveAnswer(
        @PathVariable Long attemptId,
        @RequestBody SaveAnswerRequest request
    ) {
        Attempt attempt = loadOwnAttempt(attemptId);

        // --- reject answers after the server-side deadline ---
        if (Instant.now().isAfter(attempt.getEndedAt())) {
            throw new ExamExpiredException("This exam has already ended.");
        }
        if (attempt.getSubmitted()) {
            throw new ExamExpiredException("This attempt is already submitted.");
        }

        Question question = questionRepository.findById(request.questionId())
            .orElseThrow(() -> new ResourceNotFoundException("Question not found"));

        // Find an existing answer for this question in this attempt (re-answering
        // updates it instead of creating a duplicate row) or make a new one.
        StudentAnswer answer = studentAnswerRepository
            .findAll()
            .stream()
            .filter(a -> a.getAttempt() != null && a.getQuestion() != null && a.getAttempt().getId().equals(attemptId) && a.getQuestion().getId().equals(question.getId()))
            .findFirst()
            .orElseGet(() -> {
                StudentAnswer a = new StudentAnswer();
                a.setAttempt(attempt);
                a.setQuestion(question);
                return a;
            });
        answer.setSelectedOptionIndex(request.selectedOptionIndex());
        studentAnswerRepository.save(answer);

        return ResponseEntity.ok(new SaveAnswerResponse(true, Instant.now()));
    }

    // =====================================================================
    // RULE 3: Submit + grading logic
    // POST /api/attempts/{attemptId}/submit
    // =====================================================================
    @PostMapping("/attempts/{attemptId}/submit")
    public ResponseEntity<SubmitResponse> submit(@PathVariable Long attemptId) {
        Attempt attempt = loadOwnAttempt(attemptId);
        if (attempt.getSubmitted()) {
            throw new ExamExpiredException("This attempt is already submitted.");
        }
        int score = gradeAttempt(attempt);
        attempt.setSubmitted(true);
        attempt.setScore(score);
        attemptRepository.save(attempt);

        int total = (int) questionRepository
            .findAll()
            .stream()
            .filter(q -> q.getExam() != null && attempt.getExam() != null && q.getExam().getId().equals(attempt.getExam().getId()))
            .count();

        return ResponseEntity.ok(new SubmitResponse(score, total));
    }

    /**
     * The actual grading: loop through every saved answer for this attempt,
     * compare selectedOptionIndex to the question's correctOptionIndex,
     * count how many match. This is server-side ONLY — the student never
     * sees correctOptionIndex until after this runs.
     */
    private int gradeAttempt(Attempt attempt) {
        List<StudentAnswer> answers = studentAnswerRepository
            .findAll()
            .stream()
            .filter(a -> a.getAttempt() != null && a.getAttempt().getId().equals(attempt.getId()))
            .collect(Collectors.toList());

        int score = 0;
        for (StudentAnswer answer : answers) {
            if (answer.getQuestion() != null && answer.getSelectedOptionIndex() == answer.getQuestion().getCorrectOptionIndex()) {
                score++;
            }
        }
        return score;
    }

    // =====================================================================
    // Review — safe to reveal correct answers now that it's submitted
    // GET /api/attempts/{attemptId}/review
    // =====================================================================
    @Transactional
    @GetMapping("/attempts/{attemptId}/review")
    public ResponseEntity<List<ReviewItem>> review(@PathVariable Long attemptId) {
        Attempt attempt = loadOwnAttempt(attemptId);
        if (!attempt.getSubmitted()) {
            throw new ExamExpiredException("Submit the exam before viewing the review.");
        }

        List<Question> questions = questionRepository
            .findAll()
            .stream()
            .filter(q -> q.getExam() != null && attempt.getExam() != null && q.getExam().getId().equals(attempt.getExam().getId()))
            .collect(Collectors.toList());

        List<StudentAnswer> answers = studentAnswerRepository
            .findAll()
            .stream()
            .filter(a -> a.getAttempt() != null && a.getAttempt().getId().equals(attemptId))
            .collect(Collectors.toList());

        List<ReviewItem> items = questions.stream().map(q -> {
            List<String> optionTexts = q.getQuestionOptions()
                .stream()
                .sorted(Comparator.comparingInt(QuestionOption::getOrderIndex))
                .map(QuestionOption::getText)
                .collect(Collectors.toList());

            Integer selected = answers.stream()
                .filter(a -> a.getQuestion() != null && a.getQuestion().getId().equals(q.getId()))
                .map(StudentAnswer::getSelectedOptionIndex)
                .findFirst()
                .orElse(null);

            return new ReviewItem(q.getText(), optionTexts, q.getCorrectOptionIndex(), selected);
        }).collect(Collectors.toList());

        return ResponseEntity.ok(items);
    }

    // =====================================================================
    // RULE: Proctoring endpoint
    // POST /api/attempts/{attemptId}/events
    // =====================================================================
    @PostMapping("/attempts/{attemptId}/events")
    public ResponseEntity<ProctorEventResponse> recordEvent(
        @PathVariable Long attemptId,
        @RequestBody ProctorEventRequest request
    ) {
        Attempt attempt = loadOwnAttempt(attemptId);

        ProctorEvent event = new ProctorEvent();
        event.setAttempt(attempt);
        event.setEventType(request.type()); // e.g. "TAB_SWITCH"
        event.setTimestamp(Instant.now());
        proctorEventRepository.save(event);

        return ResponseEntity.ok(new ProctorEventResponse(true));
    }

    // =====================================================================
    // RULE: Live dashboard for the teacher
    // GET /api/exams/{examId}/live
    // =====================================================================
    @Transactional
    @GetMapping("/exams/{examId}/live")
    
    public ResponseEntity<List<LiveStudentStatus>> live(@PathVariable Long examId) {
        Exam exam = examRepository.findById(examId)
            .orElseThrow(() -> new ResourceNotFoundException("Exam not found: " + examId));

        int totalQuestions = (int) questionRepository
            .findAll()
            .stream()
            .filter(q -> q.getExam() != null && q.getExam().getId().equals(examId))
            .count();

        List<Attempt> attempts = attemptRepository
            .findAll()
            .stream()
            .filter(a -> a.getExam() != null && a.getExam().getId().equals(examId))
            .collect(Collectors.toList());

        List<LiveStudentStatus> result = attempts.stream().map(a -> {
            int answered = (int) studentAnswerRepository
                .findAll()
                .stream()
                .filter(ans -> ans.getAttempt() != null && ans.getAttempt().getId().equals(a.getId()))
                .count();

            int tabSwitches = (int) proctorEventRepository
                .findAll()
                .stream()
                .filter(ev -> ev.getAttempt() != null && ev.getAttempt().getId().equals(a.getId()) && "TAB_SWITCH".equals(ev.getEventType()))
                .count();

            return new LiveStudentStatus(
                a.getStudent().getLogin(),
                a.getSubmitted() ? "SUBMITTED" : "IN_PROGRESS",
                answered,
                totalQuestions,
                tabSwitches,
                a.getScore()
            );
        }).collect(Collectors.toList());

        return ResponseEntity.ok(result);
    }

    // =====================================================================
    // Shared helper: load an attempt AND check it belongs to the caller.
    // Prevents student A from reading/editing student B's attempt by
    // guessing an attemptId in the URL.
    // =====================================================================
    private Attempt loadOwnAttempt(Long attemptId) {
        Attempt attempt = attemptRepository.findById(attemptId)
            .orElseThrow(() -> new ResourceNotFoundException("Attempt not found: " + attemptId));
        User me = currentUser();
        if (!attempt.getStudent().getId().equals(me.getId())) {
            throw new UnauthorizedAccessException("This attempt does not belong to you.");
        }
        return attempt;
    }
}