package com.examguard.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AttemptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttemptAllPropertiesEquals(Attempt expected, Attempt actual) {
        assertAttemptAutoGeneratedPropertiesEquals(expected, actual);
        assertAttemptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttemptAllUpdatablePropertiesEquals(Attempt expected, Attempt actual) {
        assertAttemptUpdatableFieldsEquals(expected, actual);
        assertAttemptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttemptAutoGeneratedPropertiesEquals(Attempt expected, Attempt actual) {
        assertThat(actual)
            .as("Verify Attempt auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttemptUpdatableFieldsEquals(Attempt expected, Attempt actual) {
        assertThat(actual)
            .as("Verify Attempt relevant properties")
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getEndedAt()).as("check endedAt").isEqualTo(expected.getEndedAt()))
            .satisfies(a -> assertThat(a.getSubmitted()).as("check submitted").isEqualTo(expected.getSubmitted()))
            .satisfies(a -> assertThat(a.getScore()).as("check score").isEqualTo(expected.getScore()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAttemptUpdatableRelationshipsEquals(Attempt expected, Attempt actual) {
        assertThat(actual)
            .as("Verify Attempt relationships")
            .satisfies(a -> assertThat(a.getExam()).as("check exam").isEqualTo(expected.getExam()));
    }
}
