package com.examguard.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProctorEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProctorEventAllPropertiesEquals(ProctorEvent expected, ProctorEvent actual) {
        assertProctorEventAutoGeneratedPropertiesEquals(expected, actual);
        assertProctorEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProctorEventAllUpdatablePropertiesEquals(ProctorEvent expected, ProctorEvent actual) {
        assertProctorEventUpdatableFieldsEquals(expected, actual);
        assertProctorEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProctorEventAutoGeneratedPropertiesEquals(ProctorEvent expected, ProctorEvent actual) {
        assertThat(actual)
            .as("Verify ProctorEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProctorEventUpdatableFieldsEquals(ProctorEvent expected, ProctorEvent actual) {
        assertThat(actual)
            .as("Verify ProctorEvent relevant properties")
            .satisfies(a -> assertThat(a.getEventType()).as("check eventType").isEqualTo(expected.getEventType()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProctorEventUpdatableRelationshipsEquals(ProctorEvent expected, ProctorEvent actual) {
        assertThat(actual)
            .as("Verify ProctorEvent relationships")
            .satisfies(a -> assertThat(a.getAttempt()).as("check attempt").isEqualTo(expected.getAttempt()));
    }
}
