package com.examguard.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StudentAnswerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentAnswerAllPropertiesEquals(StudentAnswer expected, StudentAnswer actual) {
        assertStudentAnswerAutoGeneratedPropertiesEquals(expected, actual);
        assertStudentAnswerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentAnswerAllUpdatablePropertiesEquals(StudentAnswer expected, StudentAnswer actual) {
        assertStudentAnswerUpdatableFieldsEquals(expected, actual);
        assertStudentAnswerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentAnswerAutoGeneratedPropertiesEquals(StudentAnswer expected, StudentAnswer actual) {
        assertThat(actual)
            .as("Verify StudentAnswer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentAnswerUpdatableFieldsEquals(StudentAnswer expected, StudentAnswer actual) {
        assertThat(actual)
            .as("Verify StudentAnswer relevant properties")
            .satisfies(a ->
                assertThat(a.getSelectedOptionIndex()).as("check selectedOptionIndex").isEqualTo(expected.getSelectedOptionIndex())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentAnswerUpdatableRelationshipsEquals(StudentAnswer expected, StudentAnswer actual) {
        assertThat(actual)
            .as("Verify StudentAnswer relationships")
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()))
            .satisfies(a -> assertThat(a.getAttempt()).as("check attempt").isEqualTo(expected.getAttempt()));
    }
}
